import "./globals.css"
import type { Metadata } from "next"
import { Header } from "../lib/components/layout/header/Header"
import { Footer } from "../lib/components/layout/footer/Footer"

export const metadata: Metadata = {
  title: "KS Interior",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className="w-full min-h-screen min-w-[1280px]">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
